name: Run AUtomated Tests

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout todolist APP
        uses: actions/chackout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: checkout test repo
        run: git clone https://github.com/LuisAlejandroRe/todoism-test.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install tests deps
        run: |
          cd todoism-test
          npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
